apiVersion: crossfaas.io/v1alpha1
kind: Database
metadata:
  name: my-db
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: db-conn
    namespace: openfaas-fn